allowed-mailing-lists-domains = [
    "rust-lang.org",
    "crates.io",
    "docs.rs",
    "rust-embedded.org",
    "rustconf.com",
]

allowed-github-orgs = [
    "bors-rs",
    "conduit-rust",
    "rust-lang",
    "rust-lang-ci",
    "rust-lang-nursery",
    "rust-lang-deprecated",
    "rust-dev-tools",
    "rust-embedded",
    "rust-analyzer",
]

allowed-domains = [
    "https://(.*)rust-lang.org/?.*",
    "https://areweasyncyet.rs/?.*",
    "https://crates.io/?.*",
    "https://docs.rs/?.*",
    "https://github.com/rust-lang/?.*",
    "https://rfcbot.rs/?.*",
    "https://rust-analyzer.github.io/?.*",
    "https://rust-lang.github.io/?.*",
    "https://www.arewewebyet.org/?.*",
]

permissions-bors-repos = [
    "bors-kindergarten",
    "cargo",
    "chalk",
    "clippy",
    "compiler-builtins",
    "crater",
    "hashbrown",
    "measureme",
    "miri",
    "libc",
    "regex",
    "rls",
    "rust",
    "rust-analyzer",
    "rustlings",
    "rustup-rs",
    "semverver",
    "stdarch",
    "team",
    "vscode-rust",
]

permissions-bools = [
    "perf",
    "crater",
    "crates-io-admin",
    "dev-desktop",
    "sync-team-confirmation",
]
