org = "rust-lang"
name = "initiative-template"
description = "A template for lang-team initiatives"
homepage = "https://rust-lang.github.io/initiative-template/"
bots = []

[access.teams]
lang = "maintain"
