org = "rust-lang"
name = "lang-team"
description = "Home of the Rust lang team"
homepage = "https://lang-team.rust-lang.org/"
bots = ["rustbot", "rfcbot"]

[access.teams]
lang = "maintain"
lang-ops = "maintain"
lang-docs = "maintain"
types = "maintain"
release = "maintain"
